# Generated by Django 6.1.1 on 2026-10-03 13:33

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('assessment_paper_id', models.UUIDField(db_index=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluated'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=32)),
                ('submission_reason', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('TIMEOUT', 'Timeout'), ('ADMIN_FORCED', 'Admin Forced')], max_length=32, null=True)),
                ('scoring_policy_version', models.CharField(default='v1', max_length=16)),
                ('score_floor_policy', models.CharField(choices=[('UNRESTRICTED', 'Unrestricted'), ('ZERO_FLOOR_TOTAL', 'Zero Floor Total'), ('ZERO_FLOOR_SECTION', 'Zero Floor Section')], default='UNRESTRICTED', max_length=32)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.UUIDField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('presentation_seed', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'attempt',
                'verbose_name_plural': 'attempts',
                'db_table': 'attempts_attempt',
                'indexes': [models.Index(fields=['student_id', 'status'], name='idx_attempt_student_status'), models.Index(fields=['assessment_paper_id', 'status'], name='idx_attempt_paper_status'), models.Index(fields=['expires_at'], name='idx_attempt_expires_at')],
                'constraints': [models.UniqueConstraint(fields=('student_id', 'assessment_paper_id', 'attempt_number'), name='uq_attempt_student_paper_attempt_number'), models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='chk_attempt_attempt_number_positive'), models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 1)), name='chk_attempt_duration_seconds_positive'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('cancellation_reason__isnull', False), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('cancellation_reason__isnull', True)), _connector='OR'), name='chk_attempt_cancellation_metadata')],
            },
        ),
        migrations.CreateModel(
            name='AttemptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper_item_id', models.UUIDField()),
                ('assessment_section_id', models.UUIDField(blank=True, null=True)),
                ('question_id', models.UUIDField()),
                ('question_version_id', models.UUIDField()),
                ('presentation_order', models.PositiveIntegerField()),
                ('allocated_marks', models.DecimalField(decimal_places=4, max_digits=8)),
                ('allocated_penalty', models.DecimalField(decimal_places=4, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attempts.attempt')),
            ],
            options={
                'verbose_name': 'attempt item',
                'verbose_name_plural': 'attempt items',
                'db_table': 'attempts_attempt_item',
            },
        ),
        migrations.CreateModel(
            name='AttemptEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_state', models.CharField(choices=[('UNATTEMPTED', 'Unattempted'), ('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect'), ('PARTIALLY_CORRECT', 'Partially Correct'), ('PENDING_EVALUATION', 'Pending Evaluation')], max_length=32)),
                ('marks_awarded', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('marks_deducted', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('net_marks', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('evaluator_id', models.UUIDField(blank=True, null=True)),
                ('evaluation_comments', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='attempts.attemptitem')),
            ],
            options={
                'verbose_name': 'attempt evaluation',
                'verbose_name_plural': 'attempt evaluations',
                'db_table': 'attempts_attempt_evaluation',
            },
        ),
        migrations.CreateModel(
            name='AttemptItemChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_id', models.UUIDField()),
                ('presented_position', models.PositiveIntegerField()),
                ('attempt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='attempts.attemptitem')),
            ],
            options={
                'verbose_name': 'attempt item choice',
                'verbose_name_plural': 'attempt item choices',
                'db_table': 'attempts_attempt_item_choice',
            },
        ),
        migrations.CreateModel(
            name='AttemptResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_state', models.CharField(choices=[('UNANSWERED', 'Unanswered'), ('ANSWERED', 'Answered')], default='UNANSWERED', max_length=16)),
                ('boolean_response', models.BooleanField(blank=True, null=True)),
                ('assertion_reason_response', models.CharField(blank=True, choices=[('BOTH_TRUE_REASON_CORRECT', 'Both Assertion and Reason are true, and Reason is the correct explanation of Assertion'), ('BOTH_TRUE_REASON_NOT_CORRECT', 'Both Assertion and Reason are true, but Reason is NOT the correct explanation of Assertion'), ('ASSERTION_TRUE_REASON_FALSE', 'Assertion is true, but Reason is false'), ('ASSERTION_FALSE_REASON_FALSE', 'Assertion is false, and Reason is false')], max_length=64, null=True)),
                ('text_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='attempts.attemptitem')),
            ],
            options={
                'verbose_name': 'attempt response',
                'verbose_name_plural': 'attempt responses',
                'db_table': 'attempts_attempt_response',
            },
        ),
        migrations.CreateModel(
            name='AttemptResponseChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_id', models.UUIDField()),
                ('attempt_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='attempts.attemptresponse')),
            ],
            options={
                'verbose_name': 'attempt response choice',
                'verbose_name_plural': 'attempt response choices',
                'db_table': 'attempts_attempt_response_choice',
            },
        ),
        migrations.CreateModel(
            name='AttemptResponseMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left_item_id', models.UUIDField()),
                ('right_item_id', models.UUIDField()),
                ('attempt_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='attempts.attemptresponse')),
            ],
            options={
                'verbose_name': 'attempt response match',
                'verbose_name_plural': 'attempt response matches',
                'db_table': 'attempts_attempt_response_match',
            },
        ),
        migrations.CreateModel(
            name='AttemptResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FINAL', 'Final'), ('VOID', 'Void')], default='PENDING', max_length=16)),
                ('raw_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('correct_questions', models.PositiveIntegerField(default=0)),
                ('incorrect_questions', models.PositiveIntegerField(default=0)),
                ('partially_correct_questions', models.PositiveIntegerField(default=0)),
                ('unanswered_questions', models.PositiveIntegerField(default=0)),
                ('pending_evaluation_questions', models.PositiveIntegerField(default=0)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='attempts.attempt')),
            ],
            options={
                'verbose_name': 'attempt result',
                'verbose_name_plural': 'attempt results',
                'db_table': 'attempts_attempt_result',
            },
        ),
        migrations.CreateModel(
            name='AttemptSectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_section_id', models.UUIDField()),
                ('section_title_snapshot', models.CharField(max_length=255)),
                ('section_order_snapshot', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('correct_questions', models.PositiveIntegerField(default=0)),
                ('incorrect_questions', models.PositiveIntegerField(default=0)),
                ('partially_correct_questions', models.PositiveIntegerField(default=0)),
                ('unanswered_questions', models.PositiveIntegerField(default=0)),
                ('pending_evaluation_questions', models.PositiveIntegerField(default=0)),
                ('attempt_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_results', to='attempts.attemptresult')),
            ],
            options={
                'verbose_name': 'attempt section result',
                'verbose_name_plural': 'attempt section results',
                'db_table': 'attempts_attempt_section_result',
            },
        ),
        migrations.AddIndex(
            model_name='attemptitem',
            index=models.Index(fields=['attempt', 'presentation_order'], name='idx_attempt_item_order'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'presentation_order'), name='uq_attempt_item_attempt_presentation_order'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'paper_item_id'), name='uq_attempt_item_attempt_paper_item'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.CheckConstraint(condition=models.Q(('presentation_order__gte', 1)), name='chk_attempt_item_presentation_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_marks__gte', Decimal('0.0000'))), name='chk_attempt_item_allocated_marks_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_penalty__gte', Decimal('0.0000'))), name='chk_attempt_item_allocated_penalty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attemptevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('marks_awarded__gte', Decimal('0.0000'))), name='chk_attempt_eval_marks_awarded_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attemptevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('marks_deducted__gte', Decimal('0.0000'))), name='chk_attempt_eval_marks_deducted_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attemptevaluation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evaluation_state__in', ['PENDING_EVALUATION', 'UNATTEMPTED']), ('evaluated_at__isnull', True), ('evaluator_id__isnull', True)), models.Q(('evaluation_state__in', ['CORRECT', 'INCORRECT']), ('evaluated_at__isnull', False)), models.Q(('evaluation_state', 'PARTIALLY_CORRECT'), ('evaluated_at__isnull', False), ('evaluator_id__isnull', False)), _connector='OR'), name='chk_attempt_eval_state_evaluated_at'),
        ),
        migrations.AddIndex(
            model_name='attemptitemchoice',
            index=models.Index(fields=['attempt_item', 'presented_position'], name='idx_attempt_choice_pos'),
        ),
        migrations.AddConstraint(
            model_name='attemptitemchoice',
            constraint=models.UniqueConstraint(fields=('attempt_item', 'presented_position'), name='uq_attempt_item_choice_item_presented_position'),
        ),
        migrations.AddConstraint(
            model_name='attemptitemchoice',
            constraint=models.UniqueConstraint(fields=('attempt_item', 'choice_id'), name='uq_attempt_item_choice_item_choice_id'),
        ),
        migrations.AddConstraint(
            model_name='attemptitemchoice',
            constraint=models.CheckConstraint(condition=models.Q(('presented_position__gte', 1)), name='chk_attempt_item_choice_presented_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptresponsechoice',
            constraint=models.UniqueConstraint(fields=('attempt_response', 'choice_id'), name='uq_attempt_response_choice_response_choice'),
        ),
        migrations.AddConstraint(
            model_name='attemptresponsematch',
            constraint=models.UniqueConstraint(fields=('attempt_response', 'left_item_id'), name='uq_attempt_response_match_response_left'),
        ),
        migrations.AddConstraint(
            model_name='attemptresponsematch',
            constraint=models.UniqueConstraint(fields=('attempt_response', 'right_item_id'), name='uq_attempt_response_match_response_right'),
        ),
        migrations.AddIndex(
            model_name='attemptresult',
            index=models.Index(fields=['status'], name='idx_attempt_result_status'),
        ),
        migrations.AddConstraint(
            model_name='attemptresult',
            constraint=models.CheckConstraint(condition=models.Q(('attempted_questions', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('correct_questions'), '+', models.F('incorrect_questions')), '+', models.F('partially_correct_questions')))), name='chk_attempt_result_attempted_checksum'),
        ),
        migrations.AddConstraint(
            model_name='attemptresult',
            constraint=models.CheckConstraint(condition=models.Q(('total_questions', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('attempted_questions'), '+', models.F('unanswered_questions')), '+', models.F('pending_evaluation_questions')))), name='chk_attempt_result_total_checksum'),
        ),
        migrations.AddConstraint(
            model_name='attemptresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'FINAL'), ('pending_evaluation_questions', 0), ('finalized_at__isnull', False)), models.Q(models.Q(('status', 'FINAL'), _negated=True), ('finalized_at__isnull', True)), _connector='OR'), name='chk_attempt_result_final_invariants'),
        ),
        migrations.AddIndex(
            model_name='attemptsectionresult',
            index=models.Index(fields=['attempt_result', 'assessment_section_id'], name='idx_attempt_sec_res_sec'),
        ),
        migrations.AddConstraint(
            model_name='attemptsectionresult',
            constraint=models.UniqueConstraint(fields=('attempt_result', 'assessment_section_id'), name='uq_attempt_section_result_result_section'),
        ),
        migrations.AddConstraint(
            model_name='attemptsectionresult',
            constraint=models.CheckConstraint(condition=models.Q(('section_order_snapshot__gte', 1)), name='chk_attempt_sec_res_section_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptsectionresult',
            constraint=models.CheckConstraint(condition=models.Q(('attempted_questions', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('correct_questions'), '+', models.F('incorrect_questions')), '+', models.F('partially_correct_questions')))), name='chk_attempt_sec_res_attempted_checksum'),
        ),
    ]
