# Generated by Django 6.1.1 on 2026-10-03 15:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('PRACTICE', 'Practice'), ('REVISION', 'Revision'), ('MOCK', 'Mock'), ('CUSTOM', 'Custom')], default='PRACTICE', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=32)),
                ('duration_seconds', models.PositiveIntegerField(default=3600, help_text='Configured assessment duration in seconds.')),
                ('marks_per_question', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Marks awarded per correct question.', max_digits=6)),
                ('penalty_per_question', models.DecimalField(decimal_places=2, default=Decimal('0.66'), help_text='Marks deducted per incorrect question.', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'db_table': 'assessment_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated')], default='GENERATED', max_length=32)),
                ('duration_seconds', models.PositiveIntegerField(help_text='Snapshot of duration in seconds at paper generation time.')),
                ('marks_per_question', models.DecimalField(decimal_places=2, help_text='Snapshot of marks per question at paper generation time.', max_digits=6)),
                ('penalty_per_question', models.DecimalField(decimal_places=2, help_text='Snapshot of penalty per question at paper generation time.', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='assessment.assessment')),
            ],
            options={
                'verbose_name': 'assessment paper',
                'verbose_name_plural': 'assessment papers',
                'db_table': 'assessment_paper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessment.assessment')),
            ],
            options={
                'verbose_name': 'assessment section',
                'verbose_name_plural': 'assessment sections',
                'db_table': 'assessment_section',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentPaperItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.UUIDField(db_index=True, help_text='Stable conceptual Question ID (scalar UUID).')),
                ('question_version_id', models.UUIDField(db_index=True, help_text='Exact pinned published QuestionVersion ID (scalar UUID).')),
                ('presentation_order', models.PositiveIntegerField(help_text='1-based presentation sequence of this item in the paper.')),
                ('allocated_marks', models.DecimalField(decimal_places=2, help_text='Marks allocated for answering this item correctly.', max_digits=6)),
                ('allocated_penalty', models.DecimalField(decimal_places=2, help_text='Penalty deducted for answering this item incorrectly.', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessment.assessmentpaper')),
                ('assessment_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_items', to='assessment.assessmentsection')),
            ],
            options={
                'verbose_name': 'assessment paper item',
                'verbose_name_plural': 'assessment paper items',
                'db_table': 'assessment_paper_item',
                'ordering': ['presentation_order'],
            },
        ),
        migrations.CreateModel(
            name='SelectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('DOMAIN', 'Domain'), ('SUBJECT', 'Subject'), ('CHAPTER', 'Chapter'), ('TOPIC', 'Topic')], max_length=32)),
                ('scope_id', models.UUIDField(db_index=True, help_text='Scalar UUID referencing learning taxonomy entity (Domain/Subject/Chapter/Topic).')),
                ('question_type', models.CharField(blank=True, choices=[('MCQ', 'Multiple Choice (Single Answer)'), ('MULTIPLE_SELECT', 'Multiple Select (Multiple Answers)'), ('TRUE_FALSE', 'True / False'), ('ASSERTION_REASON', 'Assertion and Reason'), ('MATCH_FOLLOWING', 'Match the Following'), ('DESCRIPTIVE', 'Descriptive / Long Answer')], max_length=32, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=16, null=True)),
                ('question_count', models.PositiveIntegerField(help_text='Number of questions to select matching these criteria.')),
                ('position', models.PositiveIntegerField(default=0, help_text='Execution/presentation order of this rule within the assessment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_rules', to='assessment.assessment')),
                ('assessment_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selection_rules', to='assessment.assessmentsection')),
            ],
            options={
                'verbose_name': 'selection rule',
                'verbose_name_plural': 'selection rules',
                'db_table': 'assessment_selection_rule',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentsection',
            constraint=models.UniqueConstraint(fields=('assessment', 'position'), name='uq_assessment_section_position'),
        ),
        migrations.AddConstraint(
            model_name='assessmentpaperitem',
            constraint=models.UniqueConstraint(fields=('paper', 'presentation_order'), name='uq_paper_item_presentation_order'),
        ),
        migrations.AddConstraint(
            model_name='assessmentpaperitem',
            constraint=models.UniqueConstraint(fields=('paper', 'question_id'), name='uq_paper_item_question_id'),
        ),
        migrations.AddConstraint(
            model_name='selectionrule',
            constraint=models.UniqueConstraint(fields=('assessment', 'position'), name='uq_selection_rule_assessment_position'),
        ),
    ]
