# Generated by Django 6.1.1 on 2026-10-03 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice (Single Answer)'), ('MULTIPLE_SELECT', 'Multiple Select (Multiple Answers)'), ('TRUE_FALSE', 'True / False'), ('ASSERTION_REASON', 'Assertion and Reason'), ('MATCH_FOLLOWING', 'Match the Following'), ('DESCRIPTIVE', 'Descriptive / Long Answer')], max_length=32)),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'question version',
                'verbose_name_plural': 'question versions',
                'db_table': 'question_bank_question_version',
                'ordering': ['question', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'question_bank_question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssertionReasonContent',
            fields=[
                ('question_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='assertion_reason_content', serialize=False, to='question_bank.questionversion')),
                ('assertion', models.TextField()),
                ('reason', models.TextField()),
                ('correct_relationship', models.CharField(choices=[('BOTH_TRUE_REASON_CORRECT', 'Both Assertion and Reason are true, and Reason is the correct explanation of Assertion'), ('BOTH_TRUE_REASON_NOT_CORRECT', 'Both Assertion and Reason are true, but Reason is NOT the correct explanation of Assertion'), ('ASSERTION_TRUE_REASON_FALSE', 'Assertion is true, but Reason is false'), ('ASSERTION_FALSE_REASON_FALSE', 'Assertion is false, and Reason is false')], max_length=64)),
            ],
            options={
                'verbose_name': 'assertion reason content',
                'verbose_name_plural': 'assertion reason contents',
                'db_table': 'question_bank_assertion_reason',
            },
        ),
        migrations.CreateModel(
            name='MatchFollowingContent',
            fields=[
                ('question_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='match_following_content', serialize=False, to='question_bank.questionversion')),
            ],
            options={
                'verbose_name': 'match following content',
                'verbose_name_plural': 'match following contents',
                'db_table': 'question_bank_match_following',
            },
        ),
        migrations.CreateModel(
            name='TrueFalseContent',
            fields=[
                ('question_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='true_false_content', serialize=False, to='question_bank.questionversion')),
                ('answer', models.BooleanField()),
            ],
            options={
                'verbose_name': 'true false content',
                'verbose_name_plural': 'true false contents',
                'db_table': 'question_bank_true_false',
            },
        ),
        migrations.CreateModel(
            name='MatchFollowingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('LEFT', 'Left Side'), ('RIGHT', 'Right Side')], max_length=8)),
                ('text', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_items', to='question_bank.questionversion')),
            ],
            options={
                'verbose_name': 'match following item',
                'verbose_name_plural': 'match following items',
                'db_table': 'question_bank_match_item',
                'ordering': ['side', 'position'],
            },
        ),
        migrations.CreateModel(
            name='MatchFollowingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_pairs', to='question_bank.matchfollowingitem')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs', to='question_bank.questionversion')),
                ('right_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_pairs', to='question_bank.matchfollowingitem')),
            ],
            options={
                'verbose_name': 'match following pair',
                'verbose_name_plural': 'match following pairs',
                'db_table': 'question_bank_match_pair',
            },
        ),
        migrations.AddField(
            model_name='questionversion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='question_bank.question'),
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_topics', to='question_bank.question')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_topics', to='learning.topic')),
            ],
            options={
                'verbose_name': 'question topic',
                'verbose_name_plural': 'question topics',
                'db_table': 'question_bank_question_topic',
            },
        ),
        migrations.CreateModel(
            name='QuestionVersionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question_bank.questionversion')),
            ],
            options={
                'verbose_name': 'question choice',
                'verbose_name_plural': 'question choices',
                'db_table': 'question_bank_choice',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DescriptiveContent',
            fields=[
                ('question_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='descriptive_content', serialize=False, to='question_bank.questionversion')),
                ('marks', models.PositiveIntegerField()),
                ('expected_answer', models.TextField()),
            ],
            options={
                'verbose_name': 'descriptive content',
                'verbose_name_plural': 'descriptive contents',
                'db_table': 'question_bank_descriptive',
                'constraints': [models.CheckConstraint(condition=models.Q(('marks__gt', 0)), name='check_positive_descriptive_marks')],
            },
        ),
        migrations.AddConstraint(
            model_name='matchfollowingitem',
            constraint=models.UniqueConstraint(fields=('question_version', 'side', 'position'), name='unique_match_item_side_pos'),
        ),
        migrations.AddConstraint(
            model_name='matchfollowingitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='check_positive_match_item_pos'),
        ),
        migrations.AddConstraint(
            model_name='matchfollowingpair',
            constraint=models.UniqueConstraint(fields=('question_version', 'left_item'), name='unique_match_pair_left'),
        ),
        migrations.AddConstraint(
            model_name='matchfollowingpair',
            constraint=models.UniqueConstraint(fields=('question_version', 'right_item'), name='unique_match_pair_right'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version_number'), name='unique_question_version_number'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gt', 0)), name='check_positive_version_number'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('question',), name='unique_published_version_per_question'),
        ),
        migrations.AddIndex(
            model_name='questiontopic',
            index=models.Index(fields=['topic', 'question'], name='idx_qtopic_topic_question'),
        ),
        migrations.AddConstraint(
            model_name='questiontopic',
            constraint=models.UniqueConstraint(fields=('question', 'topic'), name='unique_question_topic'),
        ),
        migrations.AddConstraint(
            model_name='questionversionchoice',
            constraint=models.UniqueConstraint(fields=('question_version', 'position'), name='unique_choice_version_position'),
        ),
        migrations.AddConstraint(
            model_name='questionversionchoice',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='check_positive_choice_position'),
        ),
    ]
