# Generated by Django 6.1.1 on 2026-10-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionversion',
            name='external_question_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='source_reference',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='source_type',
            field=models.CharField(blank=True, choices=[('ORIGINAL', 'Original'), ('UPSC_PREVIOUS_YEAR', 'UPSC Previous Year'), ('LICENSED', 'Licensed'), ('CONTRIBUTOR', 'Contributor'), ('AI_GENERATED', 'AI Generated'), ('IMPORTED', 'Imported')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='source_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
